name: Auto PR, Merge, Test, and Build

on:
  push:
    branches:
      - "*"  # Trigger on any push to any branch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Git configuration to create PR (needed for authentication)
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 3: Check if there are changes to commit (no changes = no need for PR)
      - name: Check for changes
        run: |
          git diff --exit-code || echo "Changes detected"

      # Step 4: Create a PR into `main` branch (only if there are changes)
      - name: Create a Pull Request if changes exist
        if: success() && steps.check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          branch: ${{ github.head_ref }}
          title: "Auto PR to main"
          body: |
            This is an auto-generated PR with recent changes.
          token: ${{ secrets.GITHUB_TOKEN }}

  merge-and-build:
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code again to the merged PR branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Merge the PR into main branch
      - name: Merge PR into main
        uses: gh actions/merge@v1
        with:
          pull_request_number: ${{ steps.create-pr.outputs.pull_request_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Run tests (for example, using npm for a Node.js project)
      - name: Run Tests
        run: npm install && npm test

      # Step 4: Build your project (for example, build with npm)
      - name: Build Project
        run: npm run build
